<script language="JavaScript">
<!--
document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta charset=/"utf-8/">");
document.writeln("<meta name=/"viewport/" content=/"width=device-width, initial-scale=1/">");
document.writeln("<style>");
document.writeln("* {box-sizing: border-box}");
document.writeln("body {font-family: Verdana, sans-serif; margin:0}");
document.writeln(".mySlides {display: none}");
document.writeln("img {vertical-align: middle;}");
document.writeln("");
document.writeln("/* Slideshow container */");
document.writeln(".slideshow-container {");
document.writeln("  max-width: 400px;");
document.writeln("  position: relative;");
document.writeln("  margin: auto;");
document.writeln("}");
document.writeln("");
document.writeln("/* Next & previous buttons */");
document.writeln(".prev, .next {");
document.writeln("  cursor: pointer;");
document.writeln("  position: absolute;");
document.writeln("  top: 50%;");
document.writeln("  width: auto;");
document.writeln("  padding: 16px;");
document.writeln("  margin-top: -22px;");
document.writeln("  color: white;");
document.writeln("  font-weight: bold;");
document.writeln("  font-size: 18px;");
document.writeln("  transition: 0.6s ease;");
document.writeln("  border-radius: 0 3px 3px 0;");
document.writeln("}");
document.writeln("");
document.writeln("/* Position the /"next button/" to the right */");
document.writeln(".next {");
document.writeln("  right: 0;");
document.writeln("  border-radius: 3px 0 0 3px;");
document.writeln("}");
document.writeln("");
document.writeln("/* On hover, add a black background color with a little bit see-through */");
document.writeln(".prev:hover, .next:hover {");
document.writeln("  background-color: rgba(0,0,0,0.8);");
document.writeln("}");
document.writeln("");
document.writeln("/* Caption text */");
document.writeln(".text {");
document.writeln("  color: #f2f2f2;");
document.writeln("  font-size: 15px;");
document.writeln("  padding: 8px 12px;");
document.writeln("  position: absolute;");
document.writeln("  bottom: 8px;");
document.writeln("  width: 100%;");
document.writeln("  text-align: center;");
document.writeln("}");
document.writeln("");
document.writeln("/* Number text (1/3 etc) */");
document.writeln(".numbertext {");
document.writeln("  color: #f2f2f2;");
document.writeln("  font-size: 12px;");
document.writeln("  padding: 8px 12px;");
document.writeln("  position: absolute;");
document.writeln("  top: 0;");
document.writeln("}");
document.writeln("");
document.writeln("/* The dots/bullets/indicators */");
document.writeln(".dot {");
document.writeln("  cursor: pointer;");
document.writeln("  height: 15px;");
document.writeln("  width: 15px;");
document.writeln("  margin: 0 2px;");
document.writeln("  background-color: #bbb;");
document.writeln("  border-radius: 50%;");
document.writeln("  display: inline-block;");
document.writeln("  transition: background-color 0.6s ease;");
document.writeln("}");
document.writeln("");
document.writeln(".active, .dot:hover {");
document.writeln("  background-color: #717171;");
document.writeln("}");
document.writeln("");
document.writeln("/* Fading animation */");
document.writeln(".fade {");
document.writeln("  -webkit-animation-name: fade;");
document.writeln("  -webkit-animation-duration: 1.5s;");
document.writeln("  animation-name: fade;");
document.writeln("  animation-duration: 1.5s;");
document.writeln("}");
document.writeln("");
document.writeln("@-webkit-keyframes fade {");
document.writeln("  from {opacity: .4} ");
document.writeln("  to {opacity: 1}");
document.writeln("}");
document.writeln("");
document.writeln("@keyframes fade {");
document.writeln("  from {opacity: .4} ");
document.writeln("  to {opacity: 1}");
document.writeln("}");
document.writeln("");
document.writeln("/* On smaller screens, decrease text size */");
document.writeln("@media only screen and (max-width: 300px) {");
document.writeln("  .prev, .next,.text {font-size: 11px}");
document.writeln("}");
document.writeln("</style>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("");
document.writeln("<div class=/"slideshow-container/">");
document.writeln("");
document.writeln("<div class=/"mySlides fade/">");
document.writeln("  <div class=/"numbertext/">1 / 3</div>");
document.writeln("  <img src=/"img_nature_wide.jpg/" style=/"width:100%/">");
document.writeln("  <div class=/"text/">Всадник</div>");
document.writeln("</div>");
document.writeln("");
document.writeln("<div class=/"mySlides fade/">");
document.writeln("  <div class=/"numbertext/">2 / 3</div>");
document.writeln("  <img src=/"img_snow_wide.jpg/" style=/"width:100%/">");
document.writeln("  <div class=/"text/">Caption Two</div>");
document.writeln("</div>");
document.writeln("");
document.writeln("<div class=/"mySlides fade/">");
document.writeln("  <div class=/"numbertext/">3 / 3</div>");
document.writeln("  <img src=/"img_mountains_wide.jpg/" style=/"width:100%/">");
document.writeln("  <div class=/"text/">Caption Three</div>");
document.writeln("</div>");
document.writeln("");
document.writeln("");
document.writeln("<a class=/"prev/" onclick=/"plusSlides(-1)/">❮</a>");
document.writeln("<a class=/"next/" onclick=/"plusSlides(1)/">❯</a>");
document.writeln("");
document.writeln("</div>");
document.writeln("<br>");
document.writeln("");
document.writeln("<div style=/"text-align:center/">");
document.writeln("  <span class=/"dot/" onclick=/"currentSlide(1)/"></span> ");
document.writeln("  <span class=/"dot/" onclick=/"currentSlide(2)/"></span> ");
document.writeln("  <span class=/"dot/" onclick=/"currentSlide(3)/"></span> ");
document.writeln("</div>");
document.writeln("");
document.writeln("<script>");
document.writeln("var slideIndex = 1;");
document.writeln("showSlides(slideIndex);");
document.writeln("");
document.writeln("function plusSlides(n) {");
document.writeln("  showSlides(slideIndex += n);");
document.writeln("}");
document.writeln("");
document.writeln("function currentSlide(n) {");
document.writeln("  showSlides(slideIndex = n);");
document.writeln("}");
document.writeln("");
document.writeln("function showSlides(n) {");
document.writeln("  var i;");
document.writeln("  var slides = document.getElementsByClassName(/"mySlides/");");
document.writeln("  var dots = document.getElementsByClassName(/"dot/");");
document.writeln("  if (n > slides.length) {slideIndex = 1}    ");
document.writeln("  if (n < 1) {slideIndex = slides.length}");
document.writeln("  for (i = 0; i < slides.length; i++) {");
document.writeln("      slides[i].style.display = /"none/";  ");
document.writeln("  }");
document.writeln("  for (i = 0; i < dots.length; i++) {");
document.writeln("      dots[i].className = dots[i].className.replace(/" active/", /"/");");
document.writeln("  }");
document.writeln("  slides[slideIndex-1].style.display = /"block/";  ");
document.writeln("  dots[slideIndex-1].className += /" active/";");
document.writeln("}");
document.writeln("</script>");
document.writeln("");
document.writeln("</body>");
document.writeln("</html>");
//-->
</script>